codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 90%
        threshold: 5%
        base: auto
    patch:
      default:
        target: 90%
        threshold: 5%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
