name: Check UV Lockfile

on:
  pull_request:

jobs:
  check-lock:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v1
        with:
          version: latest
      - name: Check that lockfile is up-to-date
        run: uv lock --check
